services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\AdminUpdateContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\ContentViewContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\ObjectStatesContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\SystemInfoContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\AdministrationContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\DashboardContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\RightMenuContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\TrashContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\ContentPreviewContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\LeftMenuContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\RolesContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\UDWContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\ContentTypeContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\NavigationContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\SearchContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\UserNotificationContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\ContentUpdateContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\NotificationContext: ~

  EzSystems\EzPlatformAdminUi\Behat\BusinessContext\SectionsContext: ~